version: '3.8'
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    restart: always
    ports:
      - ${NGINX_PORT_HTTP}:80
      - ${NGINX_PORT_HTTPS}:443
    links:
      - php
      - redis
    depends_on:
      - php
      - redis
    volumes:
      - ./docker/etc/nginx:/etc/nginx
      - ./docker/etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/var/cache/nginx:/var/cache/nginx
      - ./docker/var/log/nginx:/var/log/nginx
      - ./docker/var/log/supervisor:/var/log/supervisor

  php:
    build: .
    restart: always
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    volumes:
      - type: volume
        source: source
        target: /var/www/html
      - ./docker/etc/php/cli/php.ini:/etc/php/cli/php.ini
      - ./docker/etc/php/fpm/php.ini:/etc/php/fpm/php.ini
      - ./docker/etc/php/fpm/php-fpm.conf:/etc/php/fpm/php-fpm.conf
      - ./docker/etc/php/fpm/pool.d/www.conf:/etc/php/fpm/pool.d/www.conf
      - ./docker/etc/php/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/var/log/php/:/var/log/php/
      - ./docker/etc/supervisor/conf.d/:/etc/supervisor/conf.d/
      - ./docker/var/log/supervisor:/var/log/supervisor

  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    ports:
      - ${MYSQL_PORT}:${MYSQL_DEFAULT_PORT}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker/var/lib/mysql:/var/lib/mysql

  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    volumes:
      - ./docker/redis-data:/data
      - ./docker/var/log/redis:/var/log/redis
      - ./docker/etc/redis/redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

  redis-commander:
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 127.0.0.1:11081:8081

  adminer:
    image: adminer
    depends_on:
      - mysql
    restart: always
    ports:
      - 11082:8080
volumes:
  source:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./source